services:
- docker
before_install:
- docker build -t rthomason/crowdstreet-react -f Dockerfile.dev .
script:
- docker run -e CI=true rthomason/crowdstreet-react npm run test
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-crowdstreet-react
  env: DockerCrowdstreetReact-env
  bucket_name: elasticbeanstalk:us-west-2:985477181077
  bucket_path: docker-crowdstreet-react
#  edge: true
#  cleanup: false
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
env:
  global:
  - secure: LqDAAQAX0eD3QDcqruyLv55YKHtwzCjfgdIpcH8P3HhNjc5UvVErVEo720+QgDmFlSocOi/CIxWFoFrYt2ywNn6CSVsqoYtMTZD0AlW+JeeSQCYmwT+vEuUOa4NUlFZjeZ6duJ1pJJN1TAoGDlWEuSNEouauEZ3UOP+EuRSxKsQ1qW4oqSi6/exUMhG4Rj6EGfv+iDkn2WzuvJxv2+jaLOIdyBCQT4n1ejXtnvyh8kUMR5+UMHPFu9Jxvnl9FVaf8ohgVdSF/R3Xk0Lsg2cfL5OjnPW0DIGPlVHxrbojFiyP7nv5SWGV4HEm72/hukIkvi/3I/qI7lWO4vnhwD4lmG4xIeX7Z4lbluPAkVrY0ehYoPSXB/5PhbqncFfhKevFxgsXOjqFlKcm5tfZB9XhfYKx+lc/vEGvnMWW6x5H3oisYIV8AH3nbq5yCTpnqLcgIKtMQhyF/pdpcItYryh5G17ZEMUAVZi4SVLSND7bufFsq4cQCzm4uFCLdl2l+f1EOZpIRIrtZBifmvd9QVLknOgmEqu2U6VT+4szzRf5iICDPKTZ192jZhqlxYGmVh+g/n+qvII3BDEulgeiZfomQ4/dAPwtTyXKaMT/wARtHFIhHHbSYv0QVnaIsNVckN1vXz/2DCxwRnZzfWJ0SSlIJZcvY7WLDQoMXhxwqr4TE9o=
  - secure: jVcLmPiLh0YV0tBgsoGWPq7tHgZqFu8ez6RKxeQcbU5Unl0oM9HXMrtVKScLBr0S1sCb3HnLGf3HJCeFotSly0y/aSDgnDZZj4vK4W/8GGLs/mVFKhoEFS2uWrjT6swM2Qj5enJH2fhesC76u15r9fKP4Tt+O9a2veHFV2QrpxHd33BxcGdBndkLxW5yfrJ0c089KXVIp6FN7uKiAFJKGFuMcDiYnaVtiMmqkvaIj6iZxM9t2sxil22Sd3TlE3zJdT86aRrUABOUN8WRkebR+3ulVCPyS3bVzCiWcOuND+FNbGs42L04iYE1DCXD2WquJNrNVKx2cazAluCjC8TRA36ga5tm+7JKZEdRZYc6lDpHC6o5uHuMpFYabdFHSsnm7PsAmbzMFe+bKHeNG2fI/0HrYjeIEPmrYEKWMhTI+5MIi9G45lmQXXYECfL+6wdBE0zSGvbrHm0CDtUnODhu7aGHuqMbLjtRjIuD4Wu6X+KkMkRddepZipTZX5rlkL+XrjZJNe66Iqg4Z1N42j/vunWdqT7mwaAxzuh7GmTZNNtxuWW+jF/fUnvBSFqi5kBxoFRNcBLWafEsnouRf3RJx8DEJ8RnUAt23e6CLy9YUt2r5st94a2xRNipRSUNDMkkQBQeKnL9lRhOQ8/KV4jaUFkc9Lko2UZFbanJJZi3LXg=
